version: '3.1'

services:

  pring-boot-demo:
    image: focsim/demo:20201003010615
    restart: always
    container_name: spring-boot-demo
    networks:
      - basic_service
    ports:
      - 9080:8080
    external_links:
      - mysql_focsim
    environment:
      spring.datasource.url: jdbc:mysql://mysql_focsim:3306/demo?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC

## ====== 网络配置 =======
networks:
  basic_service:
    external: true